"""runbook_index.py — deterministic generator for per-project runbook indexes.

Why this exists
---------------
The knowledge-promotion pipeline (promote_knowledge.py -> apply_inbox_decision.py)
*accumulates* runbooks under `_ai_rules/projects/<P>/runbooks/`, but neither
consumer auto-loads them:

  * Claude Code (CWD=Tools\\<P>)  -> reads `projects/<P>/CLAUDE.md`, which only
    *points at* the runbooks/ folder ("read it if you need it").
  * AnimaWorks anima              -> reads `<name>_injection.md`, which never even
    mentions the project runbooks.

So an adopted runbook accumulates but is never *consumed* — the same
"動いてるように見えて成果が配送されない" disease, shifted one stage downstream.

Fix (consumption wiring, pattern B+C):
  * This script emits a tiny **awareness manifest** `runbooks/_index.md` per
    project: each runbook = name + a one-line "when to use" trigger. `critical`
    runbooks are surfaced at the top with "read in full first".
  * `CLAUDE.md` and each anima `injection.md` `@import` that single `_index.md`,
    so every session/heartbeat *knows what exists and when to open it*.
  * The index is regenerated deterministically by apply_inbox_decision.py after
    each adopt, so adoption => awareness with no LLM drift.

The manifest contains **no nested `@import`** on purpose: the AnimaWorks loader
(`core.paths._resolve_at_imports`) is single-level, so a nested import would leak
a literal `@<path>` line into anima context. critical runbooks are therefore
*named with an instruction to read them*, not transcluded.

Usage:
    python runbook_index.py --project Affiliate
    python runbook_index.py --all          # every project under projects/
    python runbook_index.py --all --check   # exit 1 if any index is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import yaml

JST = timezone(timedelta(hours=9))

AI_RULES_ROOT = Path("E:/OneDriveBiz/Obsidian/_ai_rules")
PROJECTS_ROOT = AI_RULES_ROOT / "projects"

INDEX_NAME = "_index.md"
AUTO_MARKER = "<!-- AUTO-GENERATED by runbook_index.py — do not hand-edit; regenerated on each adopt -->"

PRIORITY_CRITICAL = "critical"
PRIORITY_NORMAL = "normal"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.DOTALL)
_EMPHASIS_RE = re.compile(r"[*_`]+")
_WS_RE = re.compile(r"\s+")
_UPDATED_RE = re.compile(r"^updated: .*$", re.M)
_PREAMBLE_RE = re.compile(r"^#{1,6}\s+For future Claude", re.I)
_HEADING_RE = re.compile(r"^#{1,6}\s+(.*)")
TRIGGER_MAXLEN = 120


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    return fm, m.group(2)


def _clean_line(s: str) -> str:
    s = _EMPHASIS_RE.sub("", s)
    s = _WS_RE.sub(" ", s).strip(" >-#").strip()
    if len(s) > TRIGGER_MAXLEN:
        s = s[: TRIGGER_MAXLEN - 1].rstrip() + "…"
    return s


def extract_trigger(fm: dict[str, Any], body: str) -> str:
    """Derive a one-line 'when to use this' trigger for a runbook.

    Priority: frontmatter summary/trigger -> `## For future Claude` preamble
    first line -> first markdown heading -> first non-empty paragraph -> "".
    """
    for key in ("summary", "trigger"):
        val = fm.get(key)
        if isinstance(val, str) and val.strip():
            return _clean_line(val)

    lines = body.splitlines()
    # `## For future Claude` preamble (ai_note_quality.md convention): take its
    # first content line — it is the search-keyword summary by design.
    for i, ln in enumerate(lines):
        if _PREAMBLE_RE.match(ln.strip()):
            for nxt in lines[i + 1 :]:
                if nxt.strip():
                    return _clean_line(nxt)
            break
    for ln in lines:
        m = _HEADING_RE.match(ln.strip())
        if m and not m.group(1).lower().startswith("for future claude"):
            return _clean_line(m.group(1))
    for ln in lines:
        if ln.strip():
            return _clean_line(ln)
    return ""


def _humanize(stem: str) -> str:
    return _clean_line(stem.replace("-", " ").replace("_", " "))


def collect_runbooks(project_dir: Path) -> list[dict[str, Any]]:
    runbooks_dir = project_dir / "runbooks"
    items: list[dict[str, Any]] = []
    if not runbooks_dir.is_dir():
        return items
    for path in sorted(runbooks_dir.glob("*.md")):
        if path.name == INDEX_NAME:
            continue
        try:
            fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        except OSError:
            continue
        trigger = extract_trigger(fm, body) or _humanize(path.stem)
        items.append(
            {
                "name": path.name,
                "priority": str(fm.get("priority", PRIORITY_NORMAL)).lower(),
                "trigger": trigger,
            }
        )
    return items


def render_index(project: str, items: list[dict[str, Any]], now: datetime) -> str:
    runbooks_abs = str(PROJECTS_ROOT / project / "runbooks")
    critical = [it for it in items if it["priority"] == PRIORITY_CRITICAL]
    normal = [it for it in items if it["priority"] != PRIORITY_CRITICAL]

    fm = (
        "---\n"
        "role: workflow\n"
        "scope: project\n"
        f"project: {project}\n"
        "priority: normal\n"
        f"updated: {now.date().isoformat()}\n"
        "---\n\n"
    )

    lines: list[str] = [
        AUTO_MARKER,
        "",
        f"# {project} runbook インデックス",
        "",
        f"このプロジェクトの runbook 一覧（全文は `{runbooks_abs}\\<name>` を Read）。",
        "新しい知見が採用されるとこのインデックスは自動再生成される。",
        "",
    ]

    if not items:
        lines += ["（runbook はまだ無い。採用されるとここに自動追記される。）", ""]
        return fm + "\n".join(lines)

    if critical:
        lines += ["## 起動時に全文必読（critical）", ""]
        for it in critical:
            lines.append(f"- **{it['name']}** — {it['trigger']}（先に全文を Read すること）")
        lines.append("")

    lines += ["## 状況別（該当時に Read）", ""]
    for it in normal:
        lines.append(f"- `{it['name']}` — {it['trigger']}")
    lines.append("")

    return fm + "\n".join(lines)


def write_index(project: str, *, now: datetime | None = None, dry_run: bool = False) -> dict[str, Any]:
    now = now or datetime.now(JST)
    project_dir = PROJECTS_ROOT / project
    runbooks_dir = project_dir / "runbooks"
    items = collect_runbooks(project_dir)
    content = render_index(project, items, now)
    index_path = runbooks_dir / INDEX_NAME

    existing = index_path.read_text(encoding="utf-8") if index_path.exists() else None
    # ignore the `updated:` line when deciding staleness so a no-op run is stable
    def _norm(t: str | None) -> str | None:
        return None if t is None else _UPDATED_RE.sub("updated: <date>", t)

    changed = _norm(existing) != _norm(content)
    res = {
        "project": project,
        "runbooks": len(items),
        "critical": sum(1 for it in items if it["priority"] == PRIORITY_CRITICAL),
        "index_path": index_path.as_posix(),
        "changed": changed,
    }
    if dry_run or not changed:
        return res
    runbooks_dir.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content, encoding="utf-8", newline="\n")
    # read-after-write
    res["verified"] = index_path.exists() and index_path.read_text(encoding="utf-8") == content
    return res


def all_projects() -> list[str]:
    if not PROJECTS_ROOT.is_dir():
        return []
    return sorted(p.name for p in PROJECTS_ROOT.iterdir() if p.is_dir())


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--project", help="single project name under projects/")
    g.add_argument("--all", action="store_true", help="regenerate every project index")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--check", action="store_true", help="exit 1 if any index would change (no write)")
    args = p.parse_args(argv)

    projects = all_projects() if args.all else [args.project]
    dry = args.dry_run or args.check
    results = [write_index(proj, dry_run=dry) for proj in projects]

    stale = [r for r in results if r["changed"]]
    for r in results:
        flag = "STALE" if r["changed"] else "ok"
        print(f"[{flag}] {r['project']}: {r['runbooks']} runbooks "
              f"({r['critical']} critical) -> {r['index_path']}")

    if args.check:
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
